### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by Miss-Inputs** [Zowayix/Meow-Launcher#65]
It is time. It is no longer crappy.

I guess I'll use this to collect name ideas:

- CoolGameLauncher
- Megan's Game Launcher
- MeowGameLauncher
- ReallyNeatoGameLauncher (could go with or without camel case)

**Comment by Miss-Inputs** [comment]
So, the thing is, it's gotta have something that can pair with a frontend, whatever I call that. Like if it was called CoolGameLauncher, you'd have a CoolGameBrowser as well... unless I don't use the launcher/browser naming scheme. Would that be confusing for end users? I don't know. I'm confused by every name, myself.

**Comment by Miss-Inputs** [comment]
"Pretty Kitty Game Launcher" has been suggested and that seems "on brand" as the kids say I dunno

**Comment by Miss-Inputs** [comment]
"Game Launchnya" w/ "Game Browsnya" for the frontend

**Comment by Arisotura** [comment]
strawberryGameLauncher

or whatever random word you think of, doesn't have to be fruit-themed

**Comment by Miss-Inputs** [comment]
I mean, meow is a random word I think of

Maybe I can combine cat naming schemes into fruit naming schemes somehow...

**Comment by Miss-Inputs** [comment]
Also Meow Launcher + Meow Shelf

Because the frontend's like a virtual game shelf I guess... kinda
