### ISSUE TITLE
None is no settings value

### ISSUE THREAD

**Issue by banemon** [Zowayix/Meow-Launcher#72]
https://github.com/Zowayix/Meow-Launcher/blob/705a45719fddce473836aabc28dfc906642bb2be/mame_helpers.py#L203

if not find mame config ,get_mame_ui_config return None,do not  MameConfigFile , so get_mame_ui_config is not settings(value)

**Comment by Miss-Inputs** [comment]
Yeah, at the moment it just sorta assumes MAME is set up and installed. I'll have to look into that, now that I apparently have users...
