### ISSUE TITLE
Custom ROM DBs for speedup

### ISSUE THREAD

**Issue by ParzivalWolfram** [Zowayix/Meow-Launcher#93]
I can compile custom ROM DBs in a format that'd have just a sum and some basic info, allowing for quick detection so you don't have to skim through a huge database for every ROM. I could also trim down existing databases to just more popular ROMs for even faster detection.

**Comment by ParzivalWolfram** [comment]
I'll test out on my fork and get back to you on my findings.

**Comment by Miss-Inputs** [comment]
So like, a smaller MAME SL type of thing? Hmm.

**Comment by Miss-Inputs** [comment]
Yeah I'm just gonna close this one I think

Been over a year… I don't think it's worth doing anyway.
